### ISSUE TITLE
Create simple State Web Template react version using latest 6.0.8 State Web Template version

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-react#1]
Use [simple eleventy repo](https://github.com/Office-of-Digital-Services/California-State-Web-Template-eleventy) for layout and structure references.

**Comment by kkoryaka** [comment]
@timothyshambra i have assigned this issue to you.

**Comment by yesenia-gtz** [comment]
**To be completed by:**
[v6 Production release](https://github.com/Office-of-Digital-Services/California-State-Web-Template/milestone/3)
 Due by December 16, 2022 
Final release of State Web Template.

**Comment by jon-grant-state-ca-gov** [comment]
- Hello World version merged to main
- Homepage for examples of React elements moved to [Github pages](https://office-of-digital-services.github.io/California-State-Web-Template-react/)
- Docs for each React element in [Wiki](https://github.com/Office-of-Digital-Services/California-State-Web-Template-react/wiki)

**Comment by yesenia-gtz** [comment]
@rkojik or @artuoma can you please review this one?

PS this should be ready for review when you are back next week. Thanks!

**Comment by jon-grant-state-ca-gov** [comment]
It should be pretty easy to get it running on your local machine.

1. Clone the repository
2. Open with IDE (VS Code, Visual Studio, Sublime Text, etc)
3. Run `npm install`
4. Run `npm start`

**Comment by yesenia-gtz** [comment]
@artuoma please review today if you can.

**Comment by carterm** [comment]
I was able to install and run it locally, but I get javascript errors. @jon-grant-state-ca-gov 

```
react-dom.development.js:86 Warning: Invalid DOM property `class`. Did you mean `className`?
Uncaught SyntaxError: Identifier 'CaGovAccordion' has already been declared (at cagov.core.js:1:1)
```

**Comment by yesenia-gtz** [comment]
@carterm @artuoma will this be ready for go-live at 330pm today?

**Comment by carterm** [comment]
It compiles, renders visually ok.  Not sure what the JS errors are referring to or what functionality is missing.  It's a separate project site is a public space, so if there are fixes to be made they could happen any time.  I don't see any reason it couldn't be included.

**Comment by yesenia-gtz** [comment]
Sounds good to me, @carterm Lets push out with V6 this afternoon, Thank you!

**Comment by jon-grant-state-ca-gov** [comment]
@carterm @yesenia-gtz I will check it out today. The invalid DOM property warning is a quick fix, and the other error sounds like the CaGovAccordion tag is being declared more than once, so I should be able to track that down.

**Comment by jon-grant-state-ca-gov** [comment]
@carterm @yesenia-gtz The issues that Carter mentioned have been resolved and the updates are in the main branch :)

**Comment by yesenia-gtz** [comment]
Thank you @jon-grant-state-ca-gov , closing this out.
